# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "PayPal"
  description: A paypal component
  icon: dynamic_form
  tags: ['form']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    id:
    heading: bookshop:generic/heading!
    description: Description text to compliment the block
  styles:
    color_group: "primary"
    content_alignment: center

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
